---

- name: "1.3.1.1 | PATCH | Ensure AppArmor is installed"
  when:
    - deb11cis_rule_1_3_1_1
    - not deb11cis_apparmor_disable
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rule_1.3.1.1
    - NIST800-53R5_AC-3
  ansible.builtin.package:
    name:
      - apparmor
      - apparmor-utils
    state: present

- name: "1.3.1.2 | PATCH | Ensure AppArmor is enabled in the bootloader configuration"
  when:
    - deb11cis_rule_1_3_1_2
    - not deb11cis_apparmor_disable
  tags:
    - level1-server
    - level1-workstation
    - scored
    - patch
    - rule_1.3.1.2
    - NIST800-53R5_AC-3
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="((?:(?!{{ item }}).)*?)"$'
    line: GRUB_CMDLINE_LINUX_DEFAULT="\1 apparmor=1 security=apparmor"
    backrefs: true
  loop:
    - apparmor=1 security=apparmor
  notify: Update-grub

# Controls 1.3.1.4 and 1.3.1.3 target the same setting and thus should not be run together.
# Because control 1.3.1.4 is stricter than 1.3.1.3, we need to change the order --
# control 1.3.1.4 then registers the fact that is has run and thus keeps 1.3.1.3 from running.

- name: "1.3.1.4 | PATCH | Ensure all AppArmor Profiles are enforcing"
  when:
    - deb11cis_rule_1_3_1_4
    - not deb11cis_apparmor_disable
  tags:
    - level2-server
    - level2-workstation
    - scored
    - patch
    - rule_1.3.1.4
    - apparmor
  block:
    - name: "1.3.1.4 | PATCH | Ensure all AppArmor Profiles are enforcing | Make sure that 1.3.1.3 is not run"
      ansible.builtin.set_fact:
        control_1_3_1_4_was_run: true
        deb11cis_apparmor_enforce_only: true
      changed_when: false

    - name: "1.3.1.4 | PATCH | Ensure all AppArmor Profiles are enforcing | Get pre apply enforce count"
      ansible.builtin.shell: apparmor_status |  grep "profiles are in enforce mode" | tr -d -c 0-9
      changed_when: false
      failed_when: false
      register: discovered_apparmor_pre_count

    - name: "1.3.1.4 | PATCH | Ensure all AppArmor Profiles are enforcing | Apply enforcing to /etc/apparmor.d profiles"
      ansible.builtin.shell: aa-enforce /etc/apparmor.d/*
      changed_when: false
      failed_when: false

    - name: "1.3.1.4 | PATCH | Ensure all AppArmor Profiles are enforcing | Get post apply enforce count"
      ansible.builtin.shell: apparmor_status |  grep "profiles are in enforce mode" | tr -d -c 0-9
      changed_when: false
      failed_when: false
      register: discovered_apparmor_post_count

    - name: "1.3.1.4 | PATCH | Ensure all AppArmor Profiles are enforcing | This flags for idempotency"
      when: discovered_apparmor_post_count.stdout | length > 0
      ansible.builtin.debug:
        msg: Changed! The profiles in /etc/apparmor.d were set to enforcing
      changed_when: true

- name: "1.3.1.3 | PATCH | Ensure all AppArmor Profiles are in enforce or complain mode"
  when:
    - deb11cis_rule_1_3_1_3
    - not deb11cis_apparmor_disable
    - not control_1_3_1_4_was_run
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rule_1.3.1.3
    - apparmor
  block:
    - name: "1.3.1.3 | AUDIT | Ensure all AppArmor Profiles are in enforce or complain | Set deb11cis_apparmor_enforce_only true for GOSS"
      when:
        - deb11cis_apparmor_mode == "enforce"
      ansible.builtin.set_fact:
        deb11cis_apparmor_enforce_only: true
      changed_when: false

    - name: "1.3.1.3 | AUDIT | Ensure all AppArmor Profiles are in enforce or complain | Set deb11cis_apparmor_enforce_only false for GOSS"
      when:
        - deb11cis_apparmor_mode == "complain"
      ansible.builtin.set_fact:
        deb11cis_apparmor_enforce_only: false
      changed_when: false

    - name: "1.3.1.3 | PATCH | Ensure all AppArmor Profiles are in enforce or complain mode | Get pre apply enforce count"
      ansible.builtin.shell: apparmor_status |  grep "profiles are in {{ deb11cis_apparmor_mode }} mode" | tr -d -c 0-9
      changed_when: false
      failed_when: false
      register: discovered_apparmor_pre_count_complain

    - name: "1.3.1.3 | PATCH | Ensure all AppArmor Profiles are in enforce or complain mode | Apply complaining/enforcing to /etc/apparmor.d profiles"
      ansible.builtin.shell: aa-{{ deb11cis_apparmor_mode }} /etc/apparmor.d/*
      changed_when: false
      failed_when: false

    - name: "1.3.1.3 | PATCH | Ensure all AppArmor Profiles are in enforce or complain mode | Get post apply enforce count"
      ansible.builtin.shell: apparmor_status |  grep "profiles are in {{ deb11cis_apparmor_mode }} mode" | tr -d -c 0-9
      changed_when: false
      failed_when: false
      register: discovered_apparmor_post_count_complain

    - name: "1.3.1.3 | PATCH | Ensure all AppArmor Profiles are in enforce or complain mode | This flags for idempotency"
      when: discovered_apparmor_post_count_complain.stdout
      ansible.builtin.debug:
        msg: Changed! The profiles in /etc/apparmor.d were set to {{ deb11cis_apparmor_mode }} mode
      changed_when: true
