---

- name: "1.1.3.1 | AUDIT | Ensure separate partition exists for /var"
  block:
      - name: "1.1.3.1 | AUDIT | Ensure separate partition exists for /var | Absent"
        ansible.builtin.debug:
            msg: "Warning!! {{ required_mount }} doesn't exist. This is a manual task"

      - name: "1.1.3.1 | WARN | Ensure separate partition exists for /var | warn_count"
        ansible.builtin.import_tasks:
            file: warning_facts.yml
  vars:
      warn_control_id: '1.1.3.1'
      required_mount: '/var'
  when:
      - required_mount not in mount_names
      - debian11cis_rule_1_1_3_1
  tags:
      - level2-server
      - level2-workstation
      - automated
      - audit
      - rule_1.1.3.1
      - var

- name: |
    "1.1.3.2 | PATCH | Ensure nodev option set on /var partition"
    "1.1.3.3 | PATCH | Ensure nosuid option set on /var partition"
  ansible.posix.mount:
      path: /var
      src: "{{ item.device }}"
      state: present
      fstype: "{{ item.fstype }}"
      opts: defaults,{% if debian11cis_rule_1_1_3_2 %}nodev,{% endif %}{% if debian11cis_rule_1_1_3_3 %}nosuid{% endif %}
  notify: Remount var
  loop: "{{ ansible_facts.mounts }}"
  loop_control:
      label: "{{ item.device }}"
  when:
      - item.mount == "/var"
      - debian11cis_rule_1_1_3_2 or
        debian11cis_rule_1_1_3_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.1.3.2
      - rule_1.1.3.3
      - var
