---

- name: "1.1.6.1 | AUDIT | Ensure separate partition exists for /var/log/audit"
  block:
      - name: "1.1.6.1 | AUDIT | Ensure separate partition exists for /var/log/audit | Absent"
        ansible.builtin.debug:
            msg: "Warning!! {{ required_mount }} doesn't exist. This is a manual task"

      - name: "1.1.6.1 | WARN | Ensure separate partition exists for /var/log/audit | warn_count"
        ansible.builtin.import_tasks:
            file: warning_facts.yml
  vars:
      warn_control_id: '1.1.6.1'
      required_mount: '/var/log/audit'
  when:
      - required_mount not in mount_names
      - debian11cis_rule_1_1_6_1
  tags:
      - level2-server
      - level2-workstation
      - automated
      - audit
      - rule_1.1.6.1
      - var_log_audit

- name: |
    "1.1.6.2 | PATCH | Ensure noexec option set on /var/log/audit partition"
    "1.1.6.3 | PATCH | Ensure nodev option set on /var/log/audit partition"
    "1.1.6.4 | PATCH | Ensure nosuid option set on /var/log/audit partition"
  ansible.posix.mount:
      path: /var/log/audit
      src: "{{ item.device }}"
      state: present
      fstype: "{{ item.fstype }}"
      opts: defaults,{% if debian11cis_rule_1_1_6_2 %}noexec,{% endif %}{% if debian11cis_rule_1_1_6_3 %}nodev,{% endif %}{% if debian11cis_rule_1_1_6_4 %}nosuid{% endif %}
  notify: Remount var_log_audit
  loop: "{{ ansible_facts.mounts }}"
  loop_control:
      label: "{{ item.device }}"
  when:
      - item.mount == "/var/log/audit"
      - debian11cis_rule_1_1_6_2 or
        debian11cis_rule_1_1_6_3 or
        debian11cis_rule_1_1_6_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.1.6.2
      - rule_1.1.6.3
      - rule_1.1.6.4
      - var_log_audit
