---

- name: "1.4.1 | PATCH | Ensure bootloader password is set"
  block:
      - name: "1.4.1 | PATCH | Ensure bootloader password is set"
        ansible.builtin.template:
            src: etc/grub.d/00_user.j2
            dest: "{{ debian11cis_grub_user_file }}"
            owner: root
            group: root
            mode: 0755
        notify: Grub update

      - name: "1.4.1 | PATCH | Ensure bootloader password is set | allow unrestricted boot"
        ansible.builtin.lineinfile:
            path: "/etc/grub.d/10_linux"
            regexp: '(^CLASS="--class gnu-linux --class gnu --class os).*"$'
            line: '\g<1> --unrestricted"'
            backrefs: true
        notify: Grub update
        when: not debian11cis_ask_passwd_to_boot
  when:
      - debian11cis_set_boot_pass
      - debian11cis_rule_1_4_1
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.4.1
      - grub

- name: "1.4.2 | PATCH | Ensure permissions on bootloader config are configured"
  block:
      - name: "1.4.2 | AUDIT | Ensure permissions on bootloader config are configured | Check for Grub file"
        ansible.builtin.stat:
            path: "{{ debian11cis_grub_file }}"
        check_mode: false
        register: debian11cis_1_4_2_grub_cfg_status

      - name: "1.4.2 | PATCH | Ensure permissions on bootloader config are configured | Set permissions"
        ansible.builtin.file:
            path: "{{ debian11cis_grub_file }}"
            owner: root
            group: root
            mode: '0400'
        when:
            - debian11cis_1_4_2_grub_cfg_status.stat.exists
  when:
      - debian11cis_rule_1_4_2
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.4.2
      - grub

- name: "1.4.3 | PATCH | Ensure authentication required for single user mode"
  ansible.builtin.user:
      name: "{{ debian11cis_grub_user }}"
      password: "{{ debian11cis_grub_user_passwd }}"
  when:
      - debian11cis_rule_1_4_3
      - debian11cis_set_grub_user_pass
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.4.3
      - passwd
      - grub
