---

- name: "1.1.10 | PATCH | Disable USB Storage"
  block:
      - block:
            - name: "1.1.10 | PATCH | Disable USB Storage | Set modprobe config"
              ansible.builtin.lineinfile:
                  path: /etc/modprobe.d/usb_storage.conf
                  regexp: '^install usb-storage'
                  line: 'install usb-storage /bin/true'
                  create: true

            - name: "1.1.10 | PATCH | Disable USB Storage | Blacklist usb-storage"
              ansible.builtin.lineinfile:
                  path: /etc/modprobe.d/blacklist.conf
                  line: 'blacklist usb-storage'
                  insertafter: EOF

            - name: "1.1.10 | PATCH | Disable USB Storage | Remove usb-storage module"
              community.general.modprobe:
                  name: usb-storage
                  state: absent
              when: ansible_connection != 'docker'
        when:
            - debian11cis_rule_1_1_10
            - not debian11cis_allow_usb_storage
            - discovered_uas_status.rc != 0
        notify: Update_Initramfs

      - name: "1.1.10 | AUDIT | Disable USB Storage | Warning Message"
        ansible.builtin.debug:
            msg:
                - "Warning!! USB Attached SCSI (UAS) support is still detected."
                - "Removing UAS may cause performance issues or prevent certain USB devices from functioning correctly."
                - "UAS provides higher speeds and better I/O performance compared to traditional USB mass storage"
                - "Ensure that this action is intentional and consider testing on non-critical systems before applying in production."
                - "Please review your setting for variable debian11cis_uas_remove and make sure it is set to true"
                - "And rerun the Ansible playbook to properly remove usb_storage."
        when:
            - debian11cis_rule_1_1_10
            - not debian11cis_allow_usb_storage
            - discovered_uas_status.rc == 0

      - name: "1.1.10 | WARN | Disable USB Storage | Warn Count"
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '1.1.10'
        when:
            - debian11cis_rule_1_1_10
            - not debian11cis_allow_usb_storage
            - discovered_uas_status.rc == 0
  when:
      - debian11cis_rule_1_1_10
  tags:
      - level1-server
      - level2-workstation
      - automated
      - patch
      - rule_1.1.10
      - usb_storage
