---

- name: "1.1.5.1 | AUDIT | Ensure separate partition exists for /var/log"
  block:
      - name: "1.1.5.1 | AUDIT | Ensure separate partition exists for /var/log | Absent"
        ansible.builtin.debug:
            msg: "Warning!! {{ required_mount }} doesn't exist. This is a manual task"

      - name: "1.1.5.1 | WARN | Ensure separate partition exists for /var/log | warn_count"
        ansible.builtin.import_tasks:
            file: warning_facts.yml
  vars:
      warn_control_id: '1.1.5.1'
      required_mount: '/var/log'
  when:
      - required_mount not in mount_names
      - debian11cis_rule_1_1_5_1
  tags:
      - level2-server
      - level2-workstation
      - automated
      - audit
      - rule_1.1.5.1
      - var_log

- name: |
    "1.1.5.2 | PATCH | Ensure nodev option set on /var/log partition"
    "1.1.5.3 | PATCH | Ensure noexec option set on /var/log partition"
    "1.1.5.4 | PATCH | Ensure nosuid option set on /var/log partition"
  ansible.posix.mount:
      path: /var/log
      src: "{{ item.device }}"
      state: present
      fstype: "{{ item.fstype }}"
      opts: defaults,{% if debian11cis_rule_1_1_5_2 %}nodev,{% endif %}{% if debian11cis_rule_1_1_5_3 %}noexec,{% endif %}{% if debian11cis_rule_1_1_5_4 %}nosuid{% endif %}
  notify: Remount var_log
  loop: "{{ ansible_facts.mounts }}"
  loop_control:
      label: "{{ item.device }}"
  when:
      - item.mount == "/var/log"
      - debian11cis_rule_1_1_5_2 or
        debian11cis_rule_1_1_5_3 or
        debian11cis_rule_1_1_5_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.1.5.2
      - rule_1.1.5.3
      - rule_1.1.5.4
      - var_log
