---

- name: "1.1.7.1 | AUDIT | Ensure separate partition exists for /home"
  block:
      - name: "1.1.7.1 | AUDIT | Ensure separate partition exists for /home | Absent"
        ansible.builtin.debug:
            msg: "Warning!! {{ required_mount }} doesn't exist. This is a manual task"

      - name: "1.1.7.1 | WARN | Ensure separate partition exists for /home | warn_count"
        ansible.builtin.import_tasks:
            file: warning_facts.yml
  vars:
      warn_control_id: '1.1.7.1'
      required_mount: '/home'
  when:
      - required_mount not in mount_names
      - debian11cis_rule_1_1_7_1
  tags:
      - level2-server
      - level2-workstation
      - automated
      - audit
      - rule_1.1.7.1
      - home

- name: |
    "1.1.7.2 | PATCH | Ensure nodev option set on /home partition"
    "1.1.7.3 | PATCH | Ensure nosuid option set on /home partition"
  ansible.posix.mount:
      path: /home
      src: "{{ item.device }}"
      state: present
      fstype: "{{ item.fstype }}"
      opts: defaults,{% if debian11cis_rule_1_1_7_2 %}nodev,{% endif %}{% if debian11cis_rule_1_1_7_3 %}nosuid{% endif %}
  notify: Remount home
  loop: "{{ ansible_facts.mounts }}"
  loop_control:
      label: "{{ item.device }}"
  when:
      - item.mount == "/home"
      - debian11cis_rule_1_1_7_2 or
        debian11cis_rule_1_1_7_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.1.7.2
      - rule_1.1.7.3
      - home
